<?php

namespace AppBundle\Repository;

/**
 * CommissionRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissionRateRepository extends \Doctrine\ORM\EntityRepository
{
}
