<?php

namespace AppBundle\Repository;

/**
 * CustomerStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
