<?php

namespace AppBundle\Repository;

/**
 * CustomerRelationshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRelationshipRepository extends \Doctrine\ORM\EntityRepository
{
}
