<?php

namespace AppBundle\Repository;

/**
 * EnterRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnterRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
