<?php

namespace AppBundle\Repository;

/**
 * FiscalYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiscalYearRepository extends \Doctrine\ORM\EntityRepository
{
}
