<?php

namespace AppBundle\Repository;

/**
 * InvoiceLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceLineRepository extends \Doctrine\ORM\EntityRepository
{
}
