<?php

namespace AppBundle\Repository;

/**
 * JobPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
