<?php

namespace AppBundle\Repository;

/**
 * LeadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadRepository extends \Doctrine\ORM\EntityRepository
{
}
