<?php

namespace AppBundle\Repository;

/**
 * LegalFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalFormRepository extends \Doctrine\ORM\EntityRepository
{
}
