<?php

namespace AppBundle\Repository;

/**
 * MissionPurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionPurchaseRepository extends \Doctrine\ORM\EntityRepository
{
}
