<?php

namespace AppBundle\Repository;

/**
 * QuotationLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationLineRepository extends \Doctrine\ORM\EntityRepository
{
}
