<?php

namespace AppBundle\Repository;

/**
 * TransmitionModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransmitionModeRepository extends \Doctrine\ORM\EntityRepository
{
}
