<?php

namespace AppBundle\Repository;

/**
 * TransmissionModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransmissionModeRepository extends \Doctrine\ORM\EntityRepository
{
}
