<?php

namespace AppBundle\Repository;

/**
 * TypeMissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMissionRepository extends \Doctrine\ORM\EntityRepository
{
}
