app_employee:
    resource: "@AppBundle/Controller/EmployeeController.php"
    type:     annotation

website_routing:
    resource: "@WebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

app_routing:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /app

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

api:
    resource: '.'
    type: 'api_platform'
    prefix: /api

app:
    resource: '@AppBundle/Action/'
    type: 'annotation'
    prefix: /api

api_login_check:
    path: /api/login_check
