parameters:
    from_email: "%mailer_user%"
    from_name: "Groupe EKO"

services:
    AppBundle\Mailer\Mailer:
        arguments: ["@mailer", "%from_email%", "%from_name%", "@templating", "%mail_admin%"]
        public: true

    AppBundle\Search\SearchEngine:
        arguments: ["@doctrine.orm.entity_manager"]

    AppBundle\Menu\Builder:
        arguments: ["@knp_menu.factory", "@security.authorization_checker"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createCustomerMenu, alias: customer }
