default_index:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: [GET, POST]

homepage:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: [GET, POST]
